### ISSUE TITLE
Stop using pysha3

### ISSUE THREAD

**Issue by 0-wiz-0** [ethereum/eth-hash#46]
According to its github README, pysha3 was only ever for python versions before 3.6 and after that, the hashlib module should be used. Please do that :)

To quote https://github.com/tiran/pysha3:
```
The pysha3 package has reached its end of life and is no longer supported.

The SHA-3 code was merged into Python 3.6 many years ago. Please use SHA-3 functions from [hashlib](https://docs.python.org/3/library/hashlib.html) module directly.
```

**Comment by kclowes** [comment]
I wish we could, but the hashlib library doesn't have the pre-NIST keccak algorithm implemented that ethereum uses. For now, we've pulled in a fork of `pysha3`, called `safe-pysha3` that is compatible with Python 3.11, and made pycryptodome the default. We've kept `safe-pysha3` because it's much faster than `pycryptodome` so users have that option if they need better performance.
